s11/Capstone Activity/S07_Activity/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('django_practice/', include('django_practice.urls')),
    path("admin/", admin.site.urls),
]

s11/Capstone Activity/django_practice/urls.py
from django.urls import path
from . import views

app_name = 'todolist'

urlpatterns = [
	path('', views.index, name='index'),
	path('register', views.register, name='register'),
	path('change_password', views.change_password, name='change_password'),
	path('login', views.login_view, name='login'),
	path('logout', views.logout_view, name='logout'),
	path('add_task', views.add_task, name='add_task'),
	path('add_event', views.add_event, name='add_event'),
	path('todo/<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	path('event/<int:eventitem_id>/', views.eventitem, name='viewevent_item'),
	path('<int:todoitem_id>/edit', views.update_task, name='update_task'),
	path('<int:todoitem_id>/delete', views.delete_task, name='delete_task'),

]

s11/Capstone Activity/django_practice/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

class EventItem(models.Model):
	event_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	event_date = models.DateField('event date')
	user = models.ForeignKey(User, on_delete=models.CASCADE, default="")

s11/Capstone Activity/django_practice/forms.py
from django import forms

class LoginForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

class AddTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

class UpdateTaskForm(forms.Form):
	task_name = forms.CharField(label='Task Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)
	status = forms.CharField(label='Status', max_length=50)

class AddEventForm(forms.Form):
	event_name = forms.CharField(label='Event Name', max_length=50)
	description = forms.CharField(label='Description', max_length=200)

class RegisterForm(forms.Form):
	username = forms.CharField(label='Username', max_length=20)
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	email = forms.CharField(label='Email', max_length=20)
	password = forms.CharField(label='Password', max_length=20)
	confirm_password = forms.CharField(label='Confirm Password', max_length=20)

class ChangePassForm(forms.Form):
	first_name = forms.CharField(label='First Name', max_length=20)
	last_name = forms.CharField(label='Last Name', max_length=20)
	password = forms.CharField(label='Password', max_length=20)

s11/Capstone Activity/django_practice/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.utils import timezone
from django.contrib.auth.hashers import make_password

from .models import ToDoItem, EventItem
from .forms import LoginForm, AddTaskForm, UpdateTaskForm, AddEventForm, RegisterForm, ChangePassForm

# Create your views here.

def index(request):
	todoitem_list = ToDoItem.objects.filter(user_id=request.user.id)
	eventitem_list = EventItem.objects.filter(user_id=request.user.id)
	context = {
		'todoitem_list': todoitem_list,
		'eventitem_list': eventitem_list,
		'user': request.user
		}

	return render(request, "todolist/index.html", context)

def todoitem(request, todoitem_id):
	todoitem = get_object_or_404(ToDoItem, pk=todoitem_id)
	return render(request, 'todolist/todoitem.html', model_to_dict(todoitem))

def eventitem(request, eventitem_id):
	eventitem = get_object_or_404(EventItem, pk=eventitem_id)
	return render(request, 'todolist/event_item.html', model_to_dict(eventitem))


def register(request):

	context = {}
	
	if request.method == 'POST':

		form = 	RegisterForm(request.POST)
		if form.is_valid() == False:
			form = LoginForm()

		else:
			username = form.cleaned_data['username']
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			email = form.cleaned_data['email']
			password = form.cleaned_data['password']
			confirm_password = form.cleaned_data['confirm_password']

			is_user_registered = User.objects.filter(username=username)

			if password == confirm_password:

				if not is_user_registered:
					hash_pass = make_password(password)
					User.objects.create(username=username, first_name=first_name,
					last_name=last_name, email=email, password=hash_pass)

					return redirect("todolist:index")
					
				else:
					context = {
					"error1": True
					}

			else:
				context = {
					"error2": True
					}		


	return render(request, 'register.html', context)

def change_password(request):

	context = {}
	

	if request.method == 'POST':

		form = 	ChangePassForm(request.POST)
		if form.is_valid() == False:
			form = ChangePassForm()

		else:
			first_name = form.cleaned_data['first_name']
			last_name = form.cleaned_data['last_name']
			password = form.cleaned_data['password']
			username = request.user.username

			is_user_registered = User.objects.filter(username=username)

			if not is_user_registered:
				context = {
					"error": True
					}
			else:
				user = User.objects.get(username=username)
				# hash_pass = make_password(password)
				user.first_name = first_name
				user.last_name = last_name
				user.set_password(password)
				user.save()	
				return redirect("todolist:index")		


	return render(request, 'change_password.html', context)

def login_view(request):
	context = {}

	if request.method == 'POST':
		form = LoginForm(request.POST)

		if form.is_valid() == False:
			form = LoginForm()

		else:
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = authenticate(username=username, password=password)
			context = {
				"username": username,
				"password": password
			}
			if user is not None:
				login(request, user)
				return redirect('todolist:index')

			else: 
				context = {
					"error": True
				}

	return render(request, 'login.html', context)
	
def logout_view(request):
	logout(request)
	return redirect('todolist:index')

def add_task(request):

	context = {}

	if request.method == 'POST':
		form = AddTaskForm(request.POST)
		if form.is_valid() == False:
			
			form = AddTaskForm()

		else:
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']

			duplicates = ToDoItem.objects.filter(task_name=task_name)

			if not duplicates:
				ToDoItem.objects.create(task_name=task_name, description=description, 
					date_created=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_task.html", context)

def update_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id)

	context = {
		"user": request.user,
		"todoitem_id": todoitem_id,
		"task_name": todoitem[0].task_name,
		"description": todoitem[0].description,
		"status": todoitem[0].status
	}

	if request.method == 'POST':
		form = UpdateTaskForm(request.POST)
		if form.is_valid() == False:
			form = UpdateTaskForm()

		else: 
			task_name = form.cleaned_data['task_name']
			description = form.cleaned_data['description']
			status = form.cleaned_data['status']

			if todoitem:
				todoitem[0].task_name = task_name
				todoitem[0].description = description
				todoitem[0].status = status	

				todoitem[0].save()
				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}
	return render(request, "todolist/update_task.html", context)

def delete_task(request, todoitem_id):
	todoitem = ToDoItem.objects.filter(pk=todoitem_id).delete()
	return redirect("todolist:index")

def add_event(request):

	context = {}

	if request.method == 'POST':
		form = AddEventForm(request.POST)
		if form.is_valid() == False:
			
			form = AddEventForm()

		else:
			event_name = form.cleaned_data['event_name']
			description = form.cleaned_data['description']

			duplicates = EventItem.objects.filter(event_name=event_name)

			if not duplicates:
				EventItem.objects.create(event_name=event_name, description=description, 
					event_date=timezone.now(), user_id=request.user.id)
				return redirect("todolist:index")

			else:
				context = {
					"error": True
				}

	return render(request, "todolist/add_event.html", context)

s11/Capstone Activity/django_practice/templates/todolist/add_event.html
{% extends 'base.html' %}

{% block title %}Add Event{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add An Event</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate event found</p>
				{% endif %}

				<form action="{% url 'todolist:add_event' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="event_name">Event Name: </label>
					<input class="form-control" id="event_name" type="text" name="event_name" value="{{event_name}}" maxlength="50" required>
				</div>

				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" id="description" name="description" value="{{ description }}" required></textarea>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Add Event">
				</div>
			
			</form>

			</div>
		</div>
	</div>
{% endblock %}

s11/Capstone Activity/django_practice/templates/todolist/add_task.html
{% extends 'base.html' %}

{% block title %}Add Task{% endblock %}

{% block content %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Add A Task</h1>
				{% if error == True %}
					<p class="text-danger">Duplicate task found</p>
				{% endif %}

				<form action="{% url 'todolist:add_task' %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="task_name">Task Name: </label>
					<input class="form-control" id="task_name" type="text" name="task_name" value="{{task_name}}" maxlength="50" required>
				</div>

				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" id="description" name="description" value="{{ description }}" required></textarea>
				</div>

				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Add Task">
				</div>
			
			</form>

			</div>
		</div>
	</div>
{% endblock %}

s11/Capstone Activity/django_practice/templates/todolist/event_item.html
{% extends 'base.html' %}

{% block title %}Event Item{% endblock %}

{% block content %}
	<div class="text-center my-3">
		<h1>{{event_name}}</h1>
		<h3>Description</h3>
		<p>{{description}}</p>
		<h3>Status</h3>
		<p>{{status}}</p>

		<button class="btn btn-warning mx-1 text-decoration-none">
			<a href="{% url 'todolist:index' %}" class="text-light
			text-decoration-none">Back To Tasks</a>
		</button>
	</div>

{% endblock %}

s11/Capstone Activity/django_practice/templates/todolist/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}


{% block content %}
	{% if user.is_anonymous == False %}
		<h1 class="text-center my-3">Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<div class="container">
			<div class="row">
				<h3 class="text-center mb-4">My Tasks</h3>
					{% if todoitem_list %}
					<ul class="list-group col-lg-2 offset-lg-5 text-center">
						{% for todoitem in todoitem_list %}
						<li class="list-group-item">
							<a href="{% url 'todolist:viewtodoitem' todoitem.id %}" 
							class="text-decoration-none">
							{{todoitem.task_name}}</a>
						</li>
						{% endfor %}
					</ul>
					{% else %}
						<p class="text-center">No Tasks have been created.</p>
					{% endif %}
			</div>
		</div>	

		<h3 class="text-center mb-3 mt-4">My Events</h3>
		{% if eventitem_list %}
		<div class="container">
			<div class="row">
					<ul class="list-group col-lg-2 offset-lg-5 text-center">
						{% for eventitem in eventitem_list %}
						<li class="list-group-item">
							<a href="{% url 'todolist:viewevent_item' eventitem.id %}" 
							class="text-decoration-none">
							{{eventitem.event_name}}
						</li>
						{% endfor %}
					</ul>
			</div>
		</div>	

		{% else %}
		<p class="text-center">No Events have been created.</p>
		{% endif %}

	{% else %}
		<h1 class="text-center my-3" >You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}"> here </a></p>
	{% endif %}

{% endblock %}

s11/Capstone Activity/django_practice/templates/todolist/todoitem.html
{% extends 'base.html' %}

{% block title %}To Do Item{% endblock %}

{% block content %}
	<div class="text-center my-3">
		<h1>{{task_name}}</h1>
		<h3>Description</h3>
		<p>{{description}}</p>
		<h3>Status</h3>
		<p>{{status}}</p>

		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:update_task' id %}" class="text-light
			text-decoration-none">Edit Task</a>
		</button>

		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:delete_task' id %}" class="text-light
			text-decoration-none">Delete Task</a>
		</button>

		<button class="btn btn-primary mx-1 text-decoration-none">
			<a href="{% url 'todolist:index' %}" class="text-light
			text-decoration-none">Back To Tasks</a>
		</button>
	</div>

{% endblock %}

s11/Capstone Activity/django_practice/templates/todolist/update_task.html
{% extends 'base.html' %}

{% block title %}Update Task{% endblock %}

{% block content %}
	{% if user.is_anonymous == False %}
	<div class="container">
		<div class="row">
			<div class="col-6 offset-3">
				<h1 class="text-center my-3">Update Task</h1>
				{% if error == True %}
					<p class="text-danger">Task not found</p>
				{% endif %}
				<form action="{% url 'todolist:update_task' todoitem_id %}" method="post">
				{% csrf_token %}

				<div class="mb-3">
					<label for="task_name">Task Name: </label>
					<input class="form-control" id="task_name" type="text" name="task_name" value="{{task_name}}" maxlength="50" required>
				</div>

				<div class="mb-3">
					<label for="description">Description: </label>
					<textarea class="form-control" id="description" name="description" value="{{description}}" required></textarea>
				</div>

				<div class="mb-3">
					<label for="status">Status: </label>
					<input class="form-control" id="status" type="text" name="status" value="{{status}}" maxlength="50" required>
				</div>


				<div class="text-center">
					<input class="btn btn-success" type="submit" value="Update Task">
				</div>
			
			</form>
			</div>
		</div>
	</div>
	{% else %}
		<h1 class="text-center my-3">You are not authorized to access this page.</h1>
		<p class="text-center">Kindly login <a href="{% url 'todolist:login' %}"> here </a></p>

	{% endif %}
{% endblock %}